---
# tasks file for docker
# Lets keep this simple

- name: Install Docker
  apt:
    name: python3-pip, docker-ce
    state: present

- name: Start Docker Service
  service:
    name: docker
    state: started

- name: Install docker python module and docker compose
  pip:
    name: docker, docker-compose

